// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proje1.Data;

#nullable disable

namespace proje1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240701193704_KategoriTabloDoldur")]
    partial class KategoriTabloDoldur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proje1.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            Name = "Kategori 4"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            Name = "Kategori 5"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 5,
                            Name = "Kategori 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
